In [1]:
import numpy as np
from scipy.spatial.transform import Rotation as R

In [2]:
# Define a rotation in Euler angles
roll = np.deg2rad(30)  # Roll: 30 degrees
pitch = np.deg2rad(45)  # Pitch: 45 degrees
yaw = np.deg2rad(60)  # Yaw: 60 degrees

In [8]:
# Create a rotation object from the Euler angles
r = R.from_euler('xyz', [roll, pitch, yaw])
r.as_matrix()

array([[ 0.35355339, -0.5732233 ,  0.73919892],
       [ 0.61237244,  0.73919892,  0.28033009],
       [-0.70710678,  0.35355339,  0.61237244]])

In [4]:
# Convert the rotation to a quaternion
quaternion = r.as_quat()
quaternion

array([0.02226003, 0.43967974, 0.36042341, 0.82236317])

In [6]:
# Convert the quaternion back to Euler angles
euler_angles = R.from_quat(quaternion).as_euler('xyz')
np.rad2deg(euler_angles)

array([30., 45., 60.])